Dev
Angjon/empresa-etl pull request #1
Opened 2024-04-22 23:16 UTC by Angjon

Added docker image.

2024-04-22 23:28 UTC, langulski requested changes

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/dag.py
> +    schedule_interval=timedelta(days=1),
nesse script ele vai executar todo dia a meia noite, é legal vc colocar o cron para mostras q sabe setar cron

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/download_data.py
> +    support_anchor = []
troque para list comprehension

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/extract_data.py
> +    def _make_folder(path) -> None:
pq essa func ta aqui se ja esta declarada no utils?

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_bronze.py
> +    new_columns = [
nome de colunas muito extenso,vc pode criar um .json contendo as configs basicas do seus dados tipo nome de colunas, tipagem e etc. exemplo:
`config/data.json`

```json

{
"bronze":{"columns":[],
                "dtypes":{}
   

}
}
```

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_bronze.py
> +    new_columns = [
obviamente vc vai ter q criar uma func auxiliar para ler esse arquivo mas acho q vale a pena

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_bronze.py
> +    print("Starting data reading")
troque para o logger

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_bronze.py
> +        print("Concating data")
existe alguns metodos no logger, por exemplo esse seria um log de informação, no caso invocaria como:
"logger.info" se for the warning ou error logger.error/logger.warning

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_raw.py
> +new_columns = [
mesma coisa, mova para um config file

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/download_data.py
> +import requests
uma boa pratica no airllow é para funções/scripts de transformações que ocorrem dentro do airflow, vc acaba declarando as dependencias dentro da funcao. exemplo:

```python

def foo():
    import re
    from datetime import datetime
    import math
     x= 1
     today = datetime.now()

```

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_bronze.py
> +    for i in range(0, len(extract_dir)):
mesma coisa, usa list comphrension

2024-04-22 23:28 UTC, langulski commented on airflow/dags/scripts/transform_silver.py
> +    motivo_column = ["situacao_cadastral", "descricao_motivo"]
declarar em um config file

2024-04-23 20:35 UTC, Angjon commented on airflow/dags/cnpj_dag/dag.py
movido para uma subpasta dentro de dags "cnpj_dag"

2024-04-23 20:36 UTC, Angjon commented on airflow/dags/cnpj_dag/scripts/download_data.py
Aplicado list comprehension

2024-04-23 20:38 UTC, Angjon commented on airflow/dags/cnpj_dag/scripts/extract_data.py
removido função declarada no arquivo , agora a função é importada do arquivo make_folder

2024-04-23 20:39 UTC, Angjon commented on airflow/dags/cnpj_dag/scripts/transform_silver.py
A referencia agora vem dos jsons na pasta config

2024-04-23 20:39 UTC, Angjon commented on airflow/dags/config/bronze_data.json
arquivo json complementar para o script transform_bronze.py

2024-04-23 20:39 UTC, Angjon commented on airflow/dags/config/silver_data.json
arquivo json complementar para o script transform_silver.py

2024-04-23 20:40 UTC, Angjon commented on airflow/dags/utils/download_file.py
função de download movida para a pasta utils

2024-04-23 20:41 UTC, Angjon commented on airflow/dags/utils/get_json.py
função para dar read em arquivos jsons

2024-04-23 20:41 UTC, Angjon commented on airflow/dags/utils/make_folder.py
função para criar pasta caso nao exista movida para pasta utils

2024-04-23 20:42 UTC, Angjon commented on airflow/dags/utils/support_dtypes.py
função auxiliar para dictcomprehension para as camadas bronze e silver

2024-04-24 16:40 UTC, langulski requested changes

2024-04-24 16:40 UTC, langulski commented on airflow/dags/cnpj_dag/dag.py
muda o nome da pasta para só cnpj, já q dags ja esta dentro de dags

2024-04-24 16:40 UTC, langulski commented on airflow/dags/cnpj_dag/scripts/download_data.py
> +    #     max_workers=num_threads_estabe
remova o codigo comentado, isso não é uma boa pratica

2024-04-24 16:40 UTC, langulski commented on airflow/dags/cnpj_dag/scripts/transform_bronze.py
> +    DOMAIN_PATH = "airflow/data/domain"
lembrei q essas variaveis vc consegue add na UI do airflow, e poderia passar esses paths comoa arguments nas funções, ficaria elegante e poderia explicar q ja esta pronto para alterações para outro tipos de pasta

2024-04-24 16:40 UTC, langulski commented on airflow/dags/config/bronze_data.json
> +            "ddd_fax":"pl.String",
boa

2024-04-24 16:40 UTC, langulski commented on airflow/dags/utils/get_json.py
acho qesses da pra mover tudo para util.py em utils, acho q nao vale a pena segmentar por arquivos

2024-04-24 16:40 UTC, langulski commented on load_data.py
> +    connection = psycopg2.connect(
load data...
aconselho vc usar nesse caso uma hook do airflow do postgresql da um olhada por favor.
https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/_api/airflow/providers/postgres/hooks/postgres/index.html

2024-04-24 18:00 UTC, Angjon commented on airflow/dags/cnpj_dag/scripts/download_data.py
> +    #     max_workers=num_threads_estabe
eu tinha comentado pra debuga, descomentado.

2024-04-25 14:23 UTC, Angjon reviewed
Finished using airflow variables

2024-04-25 14:24 UTC, merged